### ISSUE TITLE
ERROR: ! Undefined control sequence

### ISSUE THREAD

**Issue by Rahul5214** [Saipraneet/iitdthesis#1]
Compiled using `pdflatex thesis.tex` but it gives several warnings and at the end it stucks at question mark

```
LaTeX Warning: Citation `lamport:86' on page 3 undefined on input line 279.

! Undefined control sequence.
l.280 references~\citep
                       {lamport:86,sai:16} that explain how to use
?
```

**Comment by Saipraneet** [comment]
Thanks for pointing out the issue. 
Looks like I had forgotten to add the natbib package which was causing \citep to be undefined.
Closing the issue - it should be fixed now. Feel free to reopen if it doesn't work :)

**Comment by Rahul5214** [comment]
It worked. Thanks
